using System;
using System.Threading;
using System.Threading.Tasks;
using ProjectLM.Core;

namespace ProjectLM.LLM
{
    /// <summary>
    /// Describes a skill/upgrade generated by the LLM.
    /// </summary>
    [Serializable]
    public struct LlmUnlock
    {
        public string behaviorLabel;
        public string description;
        public string unlockType; // "upgrade", "path", "synergy", "evolution"
        public string unlockName;
        public string unlockEffect; // "click_damage", "auto_clicker", "defense", "resource_mult", "special"
        public float unlockValue;
        public string unlockDescription;
        public string newPath;
    }

    /// <summary>
    /// Interface for the LLM backend.
    /// Implementations: LLamaSharp (real), Dummy (testing), LiteRT (Android native).
    /// </summary>
    public interface ILLMBridge
    {
        bool IsModelReady { get; }
        Task<bool> LoadModel(string modelPath, IProgress<float> progress = null);
        Task<LlmUnlock> GenerateUnlock(BehaviorProfile profile, string behaviorSummary, int waveNumber, string[] availableUpgrades);
        Task<string> GenerateNarration(string behaviorLabel, string unlockName);
        void UnloadModel();
    }
}
